/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpicChar123DateChar125RouteImport } from './routes/$epic.{-$date}'
import { Route as EpicChar123DateChar125IndexRouteImport } from './routes/$epic.{-$date}.index'
import { Route as EpicChar123DateChar125AttentionRouteImport } from './routes/$epic.{-$date}.attention'
import { Route as EpicChar123DateChar125ConfigRouteImport } from './routes/$epic.{-$date}.config'
import { Route as EpicChar123DateChar125PeopleRouteImport } from './routes/$epic.{-$date}.people'
import { Route as EpicChar123DateChar125ReviewsRouteImport } from './routes/$epic.{-$date}.reviews'
import { Route as EpicChar123DateChar125ScopeRouteImport } from './routes/$epic.{-$date}.scope'
import { Route as EpicChar123DateChar125SignoffRouteImport } from './routes/$epic.{-$date}.signoff'
import { Route as EpicChar123DateChar125WeekRouteImport } from './routes/$epic.{-$date}.week'
import { Route as EpicChar123DateChar125FCodeRouteImport } from './routes/$epic.{-$date}.f.$code'
import { Route as EpicChar123DateChar125MIdRouteImport } from './routes/$epic.{-$date}.m.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicChar123DateChar125Route = EpicChar123DateChar125RouteImport.update({
  id: '/$epic/{-$date}',
  path: '/$epic/{-$date}',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicChar123DateChar125IndexRoute =
  EpicChar123DateChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125AttentionRoute =
  EpicChar123DateChar125AttentionRouteImport.update({
    id: '/attention',
    path: '/attention',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125ConfigRoute =
  EpicChar123DateChar125ConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125PeopleRoute =
  EpicChar123DateChar125PeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125ReviewsRoute =
  EpicChar123DateChar125ReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125ScopeRoute =
  EpicChar123DateChar125ScopeRouteImport.update({
    id: '/scope',
    path: '/scope',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125SignoffRoute =
  EpicChar123DateChar125SignoffRouteImport.update({
    id: '/signoff',
    path: '/signoff',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125WeekRoute =
  EpicChar123DateChar125WeekRouteImport.update({
    id: '/week',
    path: '/week',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125FCodeRoute =
  EpicChar123DateChar125FCodeRouteImport.update({
    id: '/f/$code',
    path: '/f/$code',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)
const EpicChar123DateChar125MIdRoute =
  EpicChar123DateChar125MIdRouteImport.update({
    id: '/m/$id',
    path: '/m/$id',
    getParentRoute: () => EpicChar123DateChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$epic/{-$date}': typeof EpicChar123DateChar125RouteWithChildren
  '/$epic/{-$date}/attention': typeof EpicChar123DateChar125AttentionRoute
  '/$epic/{-$date}/config': typeof EpicChar123DateChar125ConfigRoute
  '/$epic/{-$date}/people': typeof EpicChar123DateChar125PeopleRoute
  '/$epic/{-$date}/reviews': typeof EpicChar123DateChar125ReviewsRoute
  '/$epic/{-$date}/scope': typeof EpicChar123DateChar125ScopeRoute
  '/$epic/{-$date}/signoff': typeof EpicChar123DateChar125SignoffRoute
  '/$epic/{-$date}/week': typeof EpicChar123DateChar125WeekRoute
  '/$epic/{-$date}/': typeof EpicChar123DateChar125IndexRoute
  '/$epic/{-$date}/f/$code': typeof EpicChar123DateChar125FCodeRoute
  '/$epic/{-$date}/m/$id': typeof EpicChar123DateChar125MIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$epic/{-$date}/attention': typeof EpicChar123DateChar125AttentionRoute
  '/$epic/{-$date}/config': typeof EpicChar123DateChar125ConfigRoute
  '/$epic/{-$date}/people': typeof EpicChar123DateChar125PeopleRoute
  '/$epic/{-$date}/reviews': typeof EpicChar123DateChar125ReviewsRoute
  '/$epic/{-$date}/scope': typeof EpicChar123DateChar125ScopeRoute
  '/$epic/{-$date}/signoff': typeof EpicChar123DateChar125SignoffRoute
  '/$epic/{-$date}/week': typeof EpicChar123DateChar125WeekRoute
  '/$epic/{-$date}': typeof EpicChar123DateChar125IndexRoute
  '/$epic/{-$date}/f/$code': typeof EpicChar123DateChar125FCodeRoute
  '/$epic/{-$date}/m/$id': typeof EpicChar123DateChar125MIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$epic/{-$date}': typeof EpicChar123DateChar125RouteWithChildren
  '/$epic/{-$date}/attention': typeof EpicChar123DateChar125AttentionRoute
  '/$epic/{-$date}/config': typeof EpicChar123DateChar125ConfigRoute
  '/$epic/{-$date}/people': typeof EpicChar123DateChar125PeopleRoute
  '/$epic/{-$date}/reviews': typeof EpicChar123DateChar125ReviewsRoute
  '/$epic/{-$date}/scope': typeof EpicChar123DateChar125ScopeRoute
  '/$epic/{-$date}/signoff': typeof EpicChar123DateChar125SignoffRoute
  '/$epic/{-$date}/week': typeof EpicChar123DateChar125WeekRoute
  '/$epic/{-$date}/': typeof EpicChar123DateChar125IndexRoute
  '/$epic/{-$date}/f/$code': typeof EpicChar123DateChar125FCodeRoute
  '/$epic/{-$date}/m/$id': typeof EpicChar123DateChar125MIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$epic/{-$date}'
    | '/$epic/{-$date}/attention'
    | '/$epic/{-$date}/config'
    | '/$epic/{-$date}/people'
    | '/$epic/{-$date}/reviews'
    | '/$epic/{-$date}/scope'
    | '/$epic/{-$date}/signoff'
    | '/$epic/{-$date}/week'
    | '/$epic/{-$date}/'
    | '/$epic/{-$date}/f/$code'
    | '/$epic/{-$date}/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$epic/{-$date}/attention'
    | '/$epic/{-$date}/config'
    | '/$epic/{-$date}/people'
    | '/$epic/{-$date}/reviews'
    | '/$epic/{-$date}/scope'
    | '/$epic/{-$date}/signoff'
    | '/$epic/{-$date}/week'
    | '/$epic/{-$date}'
    | '/$epic/{-$date}/f/$code'
    | '/$epic/{-$date}/m/$id'
  id:
    | '__root__'
    | '/'
    | '/$epic/{-$date}'
    | '/$epic/{-$date}/attention'
    | '/$epic/{-$date}/config'
    | '/$epic/{-$date}/people'
    | '/$epic/{-$date}/reviews'
    | '/$epic/{-$date}/scope'
    | '/$epic/{-$date}/signoff'
    | '/$epic/{-$date}/week'
    | '/$epic/{-$date}/'
    | '/$epic/{-$date}/f/$code'
    | '/$epic/{-$date}/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpicChar123DateChar125Route: typeof EpicChar123DateChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$epic/{-$date}': {
      id: '/$epic/{-$date}'
      path: '/$epic/{-$date}'
      fullPath: '/$epic/{-$date}'
      preLoaderRoute: typeof EpicChar123DateChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$epic/{-$date}/': {
      id: '/$epic/{-$date}/'
      path: '/'
      fullPath: '/$epic/{-$date}/'
      preLoaderRoute: typeof EpicChar123DateChar125IndexRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/attention': {
      id: '/$epic/{-$date}/attention'
      path: '/attention'
      fullPath: '/$epic/{-$date}/attention'
      preLoaderRoute: typeof EpicChar123DateChar125AttentionRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/config': {
      id: '/$epic/{-$date}/config'
      path: '/config'
      fullPath: '/$epic/{-$date}/config'
      preLoaderRoute: typeof EpicChar123DateChar125ConfigRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/people': {
      id: '/$epic/{-$date}/people'
      path: '/people'
      fullPath: '/$epic/{-$date}/people'
      preLoaderRoute: typeof EpicChar123DateChar125PeopleRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/reviews': {
      id: '/$epic/{-$date}/reviews'
      path: '/reviews'
      fullPath: '/$epic/{-$date}/reviews'
      preLoaderRoute: typeof EpicChar123DateChar125ReviewsRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/scope': {
      id: '/$epic/{-$date}/scope'
      path: '/scope'
      fullPath: '/$epic/{-$date}/scope'
      preLoaderRoute: typeof EpicChar123DateChar125ScopeRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/signoff': {
      id: '/$epic/{-$date}/signoff'
      path: '/signoff'
      fullPath: '/$epic/{-$date}/signoff'
      preLoaderRoute: typeof EpicChar123DateChar125SignoffRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/week': {
      id: '/$epic/{-$date}/week'
      path: '/week'
      fullPath: '/$epic/{-$date}/week'
      preLoaderRoute: typeof EpicChar123DateChar125WeekRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/f/$code': {
      id: '/$epic/{-$date}/f/$code'
      path: '/f/$code'
      fullPath: '/$epic/{-$date}/f/$code'
      preLoaderRoute: typeof EpicChar123DateChar125FCodeRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
    '/$epic/{-$date}/m/$id': {
      id: '/$epic/{-$date}/m/$id'
      path: '/m/$id'
      fullPath: '/$epic/{-$date}/m/$id'
      preLoaderRoute: typeof EpicChar123DateChar125MIdRouteImport
      parentRoute: typeof EpicChar123DateChar125Route
    }
  }
}

interface EpicChar123DateChar125RouteChildren {
  EpicChar123DateChar125AttentionRoute: typeof EpicChar123DateChar125AttentionRoute
  EpicChar123DateChar125ConfigRoute: typeof EpicChar123DateChar125ConfigRoute
  EpicChar123DateChar125PeopleRoute: typeof EpicChar123DateChar125PeopleRoute
  EpicChar123DateChar125ReviewsRoute: typeof EpicChar123DateChar125ReviewsRoute
  EpicChar123DateChar125ScopeRoute: typeof EpicChar123DateChar125ScopeRoute
  EpicChar123DateChar125SignoffRoute: typeof EpicChar123DateChar125SignoffRoute
  EpicChar123DateChar125WeekRoute: typeof EpicChar123DateChar125WeekRoute
  EpicChar123DateChar125IndexRoute: typeof EpicChar123DateChar125IndexRoute
  EpicChar123DateChar125FCodeRoute: typeof EpicChar123DateChar125FCodeRoute
  EpicChar123DateChar125MIdRoute: typeof EpicChar123DateChar125MIdRoute
}

const EpicChar123DateChar125RouteChildren: EpicChar123DateChar125RouteChildren =
  {
    EpicChar123DateChar125AttentionRoute: EpicChar123DateChar125AttentionRoute,
    EpicChar123DateChar125ConfigRoute: EpicChar123DateChar125ConfigRoute,
    EpicChar123DateChar125PeopleRoute: EpicChar123DateChar125PeopleRoute,
    EpicChar123DateChar125ReviewsRoute: EpicChar123DateChar125ReviewsRoute,
    EpicChar123DateChar125ScopeRoute: EpicChar123DateChar125ScopeRoute,
    EpicChar123DateChar125SignoffRoute: EpicChar123DateChar125SignoffRoute,
    EpicChar123DateChar125WeekRoute: EpicChar123DateChar125WeekRoute,
    EpicChar123DateChar125IndexRoute: EpicChar123DateChar125IndexRoute,
    EpicChar123DateChar125FCodeRoute: EpicChar123DateChar125FCodeRoute,
    EpicChar123DateChar125MIdRoute: EpicChar123DateChar125MIdRoute,
  }

const EpicChar123DateChar125RouteWithChildren =
  EpicChar123DateChar125Route._addFileChildren(
    EpicChar123DateChar125RouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpicChar123DateChar125Route: EpicChar123DateChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
