/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DateRouteImport } from './routes/$date'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as DateIndexRouteImport } from './routes/$date.index'
import { Route as DateAttentionRouteImport } from './routes/$date.attention'
import { Route as DateConfigRouteImport } from './routes/$date.config'
import { Route as DatePeopleRouteImport } from './routes/$date.people'
import { Route as DateReviewsRouteImport } from './routes/$date.reviews'
import { Route as DateScopeRouteImport } from './routes/$date.scope'
import { Route as DateSignoffRouteImport } from './routes/$date.signoff'
import { Route as DateWeekRouteImport } from './routes/$date.week'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAttentionRouteImport } from './routes/_shell.attention'
import { Route as ShellConfigRouteImport } from './routes/_shell.config'
import { Route as ShellPeopleRouteImport } from './routes/_shell.people'
import { Route as ShellReviewsRouteImport } from './routes/_shell.reviews'
import { Route as ShellScopeRouteImport } from './routes/_shell.scope'
import { Route as ShellSignoffRouteImport } from './routes/_shell.signoff'
import { Route as ShellWeekRouteImport } from './routes/_shell.week'
import { Route as DateFCodeRouteImport } from './routes/$date.f.$code'
import { Route as DateMIdRouteImport } from './routes/$date.m.$id'
import { Route as ShellFCodeRouteImport } from './routes/_shell.f.$code'
import { Route as ShellMIdRouteImport } from './routes/_shell.m.$id'

const DateRoute = DateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const DateIndexRoute = DateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DateRoute,
} as any)
const DateAttentionRoute = DateAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => DateRoute,
} as any)
const DateConfigRoute = DateConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DateRoute,
} as any)
const DatePeopleRoute = DatePeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => DateRoute,
} as any)
const DateReviewsRoute = DateReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DateRoute,
} as any)
const DateScopeRoute = DateScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => DateRoute,
} as any)
const DateSignoffRoute = DateSignoffRouteImport.update({
  id: '/signoff',
  path: '/signoff',
  getParentRoute: () => DateRoute,
} as any)
const DateWeekRoute = DateWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => DateRoute,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAttentionRoute = ShellAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfigRoute = ShellConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPeopleRoute = ShellPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewsRoute = ShellReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScopeRoute = ShellScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSignoffRoute = ShellSignoffRouteImport.update({
  id: '/signoff',
  path: '/signoff',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWeekRoute = ShellWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => ShellRoute,
} as any)
const DateFCodeRoute = DateFCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => DateRoute,
} as any)
const DateMIdRoute = DateMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => DateRoute,
} as any)
const ShellFCodeRoute = ShellFCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMIdRoute = ShellMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$date': typeof DateRouteWithChildren
  '/': typeof ShellIndexRoute
  '/$date/attention': typeof DateAttentionRoute
  '/$date/config': typeof DateConfigRoute
  '/$date/people': typeof DatePeopleRoute
  '/$date/reviews': typeof DateReviewsRoute
  '/$date/scope': typeof DateScopeRoute
  '/$date/signoff': typeof DateSignoffRoute
  '/$date/week': typeof DateWeekRoute
  '/attention': typeof ShellAttentionRoute
  '/config': typeof ShellConfigRoute
  '/people': typeof ShellPeopleRoute
  '/reviews': typeof ShellReviewsRoute
  '/scope': typeof ShellScopeRoute
  '/signoff': typeof ShellSignoffRoute
  '/week': typeof ShellWeekRoute
  '/$date/': typeof DateIndexRoute
  '/$date/f/$code': typeof DateFCodeRoute
  '/$date/m/$id': typeof DateMIdRoute
  '/f/$code': typeof ShellFCodeRoute
  '/m/$id': typeof ShellMIdRoute
}
export interface FileRoutesByTo {
  '/$date/attention': typeof DateAttentionRoute
  '/$date/config': typeof DateConfigRoute
  '/$date/people': typeof DatePeopleRoute
  '/$date/reviews': typeof DateReviewsRoute
  '/$date/scope': typeof DateScopeRoute
  '/$date/signoff': typeof DateSignoffRoute
  '/$date/week': typeof DateWeekRoute
  '/attention': typeof ShellAttentionRoute
  '/config': typeof ShellConfigRoute
  '/people': typeof ShellPeopleRoute
  '/reviews': typeof ShellReviewsRoute
  '/scope': typeof ShellScopeRoute
  '/signoff': typeof ShellSignoffRoute
  '/week': typeof ShellWeekRoute
  '/$date': typeof DateIndexRoute
  '/': typeof ShellIndexRoute
  '/$date/f/$code': typeof DateFCodeRoute
  '/$date/m/$id': typeof DateMIdRoute
  '/f/$code': typeof ShellFCodeRoute
  '/m/$id': typeof ShellMIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$date': typeof DateRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/$date/attention': typeof DateAttentionRoute
  '/$date/config': typeof DateConfigRoute
  '/$date/people': typeof DatePeopleRoute
  '/$date/reviews': typeof DateReviewsRoute
  '/$date/scope': typeof DateScopeRoute
  '/$date/signoff': typeof DateSignoffRoute
  '/$date/week': typeof DateWeekRoute
  '/_shell/attention': typeof ShellAttentionRoute
  '/_shell/config': typeof ShellConfigRoute
  '/_shell/people': typeof ShellPeopleRoute
  '/_shell/reviews': typeof ShellReviewsRoute
  '/_shell/scope': typeof ShellScopeRoute
  '/_shell/signoff': typeof ShellSignoffRoute
  '/_shell/week': typeof ShellWeekRoute
  '/$date/': typeof DateIndexRoute
  '/_shell/': typeof ShellIndexRoute
  '/$date/f/$code': typeof DateFCodeRoute
  '/$date/m/$id': typeof DateMIdRoute
  '/_shell/f/$code': typeof ShellFCodeRoute
  '/_shell/m/$id': typeof ShellMIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$date'
    | '/'
    | '/$date/attention'
    | '/$date/config'
    | '/$date/people'
    | '/$date/reviews'
    | '/$date/scope'
    | '/$date/signoff'
    | '/$date/week'
    | '/attention'
    | '/config'
    | '/people'
    | '/reviews'
    | '/scope'
    | '/signoff'
    | '/week'
    | '/$date/'
    | '/$date/f/$code'
    | '/$date/m/$id'
    | '/f/$code'
    | '/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$date/attention'
    | '/$date/config'
    | '/$date/people'
    | '/$date/reviews'
    | '/$date/scope'
    | '/$date/signoff'
    | '/$date/week'
    | '/attention'
    | '/config'
    | '/people'
    | '/reviews'
    | '/scope'
    | '/signoff'
    | '/week'
    | '/$date'
    | '/'
    | '/$date/f/$code'
    | '/$date/m/$id'
    | '/f/$code'
    | '/m/$id'
  id:
    | '__root__'
    | '/$date'
    | '/_shell'
    | '/$date/attention'
    | '/$date/config'
    | '/$date/people'
    | '/$date/reviews'
    | '/$date/scope'
    | '/$date/signoff'
    | '/$date/week'
    | '/_shell/attention'
    | '/_shell/config'
    | '/_shell/people'
    | '/_shell/reviews'
    | '/_shell/scope'
    | '/_shell/signoff'
    | '/_shell/week'
    | '/$date/'
    | '/_shell/'
    | '/$date/f/$code'
    | '/$date/m/$id'
    | '/_shell/f/$code'
    | '/_shell/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DateRoute: typeof DateRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$date': {
      id: '/$date'
      path: '/$date'
      fullPath: '/$date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$date/': {
      id: '/$date/'
      path: '/'
      fullPath: '/$date/'
      preLoaderRoute: typeof DateIndexRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/attention': {
      id: '/$date/attention'
      path: '/attention'
      fullPath: '/$date/attention'
      preLoaderRoute: typeof DateAttentionRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/config': {
      id: '/$date/config'
      path: '/config'
      fullPath: '/$date/config'
      preLoaderRoute: typeof DateConfigRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/people': {
      id: '/$date/people'
      path: '/people'
      fullPath: '/$date/people'
      preLoaderRoute: typeof DatePeopleRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/reviews': {
      id: '/$date/reviews'
      path: '/reviews'
      fullPath: '/$date/reviews'
      preLoaderRoute: typeof DateReviewsRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/scope': {
      id: '/$date/scope'
      path: '/scope'
      fullPath: '/$date/scope'
      preLoaderRoute: typeof DateScopeRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/signoff': {
      id: '/$date/signoff'
      path: '/signoff'
      fullPath: '/$date/signoff'
      preLoaderRoute: typeof DateSignoffRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/week': {
      id: '/$date/week'
      path: '/week'
      fullPath: '/$date/week'
      preLoaderRoute: typeof DateWeekRouteImport
      parentRoute: typeof DateRoute
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/attention': {
      id: '/_shell/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof ShellAttentionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/config': {
      id: '/_shell/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ShellConfigRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/people': {
      id: '/_shell/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ShellPeopleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reviews': {
      id: '/_shell/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ShellReviewsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scope': {
      id: '/_shell/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ShellScopeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/signoff': {
      id: '/_shell/signoff'
      path: '/signoff'
      fullPath: '/signoff'
      preLoaderRoute: typeof ShellSignoffRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/week': {
      id: '/_shell/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof ShellWeekRouteImport
      parentRoute: typeof ShellRoute
    }
    '/$date/f/$code': {
      id: '/$date/f/$code'
      path: '/f/$code'
      fullPath: '/$date/f/$code'
      preLoaderRoute: typeof DateFCodeRouteImport
      parentRoute: typeof DateRoute
    }
    '/$date/m/$id': {
      id: '/$date/m/$id'
      path: '/m/$id'
      fullPath: '/$date/m/$id'
      preLoaderRoute: typeof DateMIdRouteImport
      parentRoute: typeof DateRoute
    }
    '/_shell/f/$code': {
      id: '/_shell/f/$code'
      path: '/f/$code'
      fullPath: '/f/$code'
      preLoaderRoute: typeof ShellFCodeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/m/$id': {
      id: '/_shell/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof ShellMIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface DateRouteChildren {
  DateAttentionRoute: typeof DateAttentionRoute
  DateConfigRoute: typeof DateConfigRoute
  DatePeopleRoute: typeof DatePeopleRoute
  DateReviewsRoute: typeof DateReviewsRoute
  DateScopeRoute: typeof DateScopeRoute
  DateSignoffRoute: typeof DateSignoffRoute
  DateWeekRoute: typeof DateWeekRoute
  DateIndexRoute: typeof DateIndexRoute
  DateFCodeRoute: typeof DateFCodeRoute
  DateMIdRoute: typeof DateMIdRoute
}

const DateRouteChildren: DateRouteChildren = {
  DateAttentionRoute: DateAttentionRoute,
  DateConfigRoute: DateConfigRoute,
  DatePeopleRoute: DatePeopleRoute,
  DateReviewsRoute: DateReviewsRoute,
  DateScopeRoute: DateScopeRoute,
  DateSignoffRoute: DateSignoffRoute,
  DateWeekRoute: DateWeekRoute,
  DateIndexRoute: DateIndexRoute,
  DateFCodeRoute: DateFCodeRoute,
  DateMIdRoute: DateMIdRoute,
}

const DateRouteWithChildren = DateRoute._addFileChildren(DateRouteChildren)

interface ShellRouteChildren {
  ShellAttentionRoute: typeof ShellAttentionRoute
  ShellConfigRoute: typeof ShellConfigRoute
  ShellPeopleRoute: typeof ShellPeopleRoute
  ShellReviewsRoute: typeof ShellReviewsRoute
  ShellScopeRoute: typeof ShellScopeRoute
  ShellSignoffRoute: typeof ShellSignoffRoute
  ShellWeekRoute: typeof ShellWeekRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellFCodeRoute: typeof ShellFCodeRoute
  ShellMIdRoute: typeof ShellMIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAttentionRoute: ShellAttentionRoute,
  ShellConfigRoute: ShellConfigRoute,
  ShellPeopleRoute: ShellPeopleRoute,
  ShellReviewsRoute: ShellReviewsRoute,
  ShellScopeRoute: ShellScopeRoute,
  ShellSignoffRoute: ShellSignoffRoute,
  ShellWeekRoute: ShellWeekRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellFCodeRoute: ShellFCodeRoute,
  ShellMIdRoute: ShellMIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DateRoute: DateRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
